### ISSUE TITLE
Edit item condition

### ISSUE THREAD

**Issue by Nathan-Silverglate** [SternDevops-Spring22-Inventory/inventory#10]
**As a** inventory manager  
 **I need** to update an item condition 
 **So that** customers know the condition of the item they are purchasing  
   
 ### Details and Assumptions
*Data model can hold this dynamic label
*Data model can be amended to reflect a change in condition (i.e. new to used)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a customer is returning an item]
 When a customer returns it
 Then the service can reflect that it is used
 ```

**Comment by richlisi** [comment]
As an inventory manager
I need to update an item condition
So that customers know the condition of the item they are purchasing

Details and Assumptions

*Data model can hold this dynamic label
*Data model can be amended to reflect a change in condition (i.e. new to used)

Given a customer returning an item
When a customer returns it
Then the service can reflect that it is used
